---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-svc-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/LiorJanus/frontend-svc-gitops